### ISSUE TITLE
error by me

### ISSUE THREAD

**Issue by felixcooler** [EvilInsultGenerator/discord-bot#22]
when i run the command npm install and then node main.js he says : internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'sqlite'
Require stack:
- C:\Users\Pc\Downloads\discord-bot-master\main.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\Users\Pc\Downloads\discord-bot-master\main.js:5:13)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Users\\Pc\\Downloads\\discord-bot-master\\main.js'←[39m ]

**Comment by EvilInsultGenerator** [comment]
Although the bot should be working with the dirty fix of #21 we have to update the bot this year to be state-of-the-art again. Please stay tuned for an update. 😎
